
GET http://localhost:3000/code-smell


###
POST http://localhost:3000/code-smell
Content-Type: application/json

{
    "id":2,
    "description":"testando"
}


###
GET http://localhost:3000/dependency-inversion


###
POST http://localhost:3000/dependency-inversion
Content-Type: application/json

{
    "id":3,
    "description":"testanado"
}